<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MunicipalitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('municipalities')->truncate();
        $municipalities = [
            ['name'=>'Boaco','city_id'=>'1'],
            ['name'=>'Camoapa','city_id'=>'1'],
            ['name'=>'San José de los Remates','city_id'=>'1'],
            ['name'=>'San Lorenzo','city_id'=>'1'],
            ['name'=>'Santa Lucia','city_id'=>'1'],
            ['name'=>'Teustepe','city_id'=>'1'],
            ['name'=>'Diriamba','city_id'=>'2'],
            ['name'=>'Dolores','city_id'=>'2'],
            ['name'=>'El Rosario','city_id'=>'2'],
            ['name'=>'Jinotepe','city_id'=>'2'],
            ['name'=>'La Conquista','city_id'=>'2'],
            ['name'=>'La Paz de Oriente','city_id'=>'2'],
            ['name'=>'San Marcos','city_id'=>'2'],
            ['name'=>'Santa Teresa','city_id'=>'2'],
            ['name'=>'Chichigalpa','city_id'=>'3'],
            ['name'=>'Chinandega','city_id'=>'3'],
            ['name'=>'Cinco Pinos','city_id'=>'3'],
            ['name'=>'Corinto','city_id'=>'3'],
            ['name'=>'El Realejo','city_id'=>'3'],
            ['name'=>'El Viejo','city_id'=>'3'],
            ['name'=>'Posoltega','city_id'=>'3'],
            ['name'=>'Puerto Morazán','city_id'=>'3'],
            ['name'=>'San Francisco del Norte','city_id'=>'3'],
            ['name'=>'San Pedro del Norte','city_id'=>'3'],
            ['name'=>'Santo Tomás del Norte','city_id'=>'3'],
            ['name'=>'Somotillo','city_id'=>'3'],
            ['name'=>'Villanueva','city_id'=>'3'],
            ['name'=>'Acoyapa','city_id'=>'4'],
            ['name'=>'Comalapa','city_id'=>'4'],
            ['name'=>'Cuapa','city_id'=>'4'],
            ['name'=>'El Coral','city_id'=>'4'],
            ['name'=>'Juigalpa','city_id'=>'4'],
            ['name'=>'La Libertad','city_id'=>'4'],
            ['name'=>'San Pedro de Lóvago','city_id'=>'4'],
            ['name'=>'Santo Domingo','city_id'=>'4'],
            ['name'=>'Santo Tomás','city_id'=>'4'],
            ['name'=>'Villa Sandino','city_id'=>'4'],
            ['name'=>'Bonanza','city_id'=>'5'],
            ['name'=>'Mulukukú','city_id'=>'5'],
            ['name'=>'Prinzapolka','city_id'=>'5'],
            ['name'=>'Puerto Cabezas','city_id'=>'5'],
            ['name'=>'Rosita','city_id'=>'5'],
            ['name'=>'Siuna','city_id'=>'5'],
            ['name'=>'Waslala','city_id'=>'5'],
            ['name'=>'Waspán','city_id'=>'5'],
            ['name'=>'Bluefields','city_id'=>'6'],
            ['name'=>'Corn Island','city_id'=>'6'],
            ['name'=>'Desembocadura de Río Grande','city_id'=>'6'],
            ['name'=>'El Ayote','city_id'=>'6'],
            ['name'=>'El Rama','city_id'=>'6'],
            ['name'=>'El Tortuguero','city_id'=>'6'],
            ['name'=>'Kukra Hill','city_id'=>'6'],
            ['name'=>'La Cruz de Río Grande','city_id'=>'6'],
            ['name'=>'Laguna de Perlas','city_id'=>'6'],
            ['name'=>'Muelle de los Bueyes','city_id'=>'6'],
            ['name'=>'Nueva Guinea','city_id'=>'6'],
            ['name'=>'Paiwas','city_id'=>'6'],
            ['name'=>'Condega','city_id'=>'7'],
            ['name'=>'Estelí','city_id'=>'7'],
            ['name'=>'La Trinidad','city_id'=>'7'],
            ['name'=>'Pueblo Nuevo','city_id'=>'7'],
            ['name'=>'San Juan de Limay','city_id'=>'7'],
            ['name'=>'San Nicolás','city_id'=>'7'],
            ['name'=>'Diriá','city_id'=>'8'],
            ['name'=>'Diriomo','city_id'=>'8'],
            ['name'=>'Granada','city_id'=>'8'],
            ['name'=>'Nandaime','city_id'=>'8'],
            ['name'=>'El Cuá','city_id'=>'9'],
            ['name'=>'Jinotega','city_id'=>'9'],
            ['name'=>'La Concordia','city_id'=>'9'],
            ['name'=>'San José de Bocay','city_id'=>'9'],
            ['name'=>'San Rafael del Norte','city_id'=>'9'],
            ['name'=>'San Sebastián de Yalí','city_id'=>'9'],
            ['name'=>'Santa María de Pantasma','city_id'=>'9'],
            ['name'=>'Wiwilí de Jinotega','city_id'=>'9'],
            ['name'=>'Achuapa','city_id'=>'10'],
            ['name'=>'El Jicaral','city_id'=>'10'],
            ['name'=>'El Sauce','city_id'=>'10'],
            ['name'=>'La Paz Centro','city_id'=>'10'],
            ['name'=>'Larreynaga','city_id'=>'10'],
            ['name'=>'León','city_id'=>'10'],
            ['name'=>'Nagarote','city_id'=>'10'],
            ['name'=>'Quezalguaque','city_id'=>'10'],
            ['name'=>'Santa Rosa del Peñón','city_id'=>'10'],
            ['name'=>'Telica','city_id'=>'10'],
            ['name'=>'Las Sabanas','city_id'=>'11'],
            ['name'=>'Palacagüina','city_id'=>'11'],
            ['name'=>'San José de Cusmapa','city_id'=>'11'],
            ['name'=>'San Juan de Río Coco','city_id'=>'11'],
            ['name'=>'San Lucas','city_id'=>'11'],
            ['name'=>'Somoto','city_id'=>'11'],
            ['name'=>'Telpaneca','city_id'=>'11'],
            ['name'=>'Totogalpa','city_id'=>'11'],
            ['name'=>'Yalagüina','city_id'=>'11'],
            ['name'=>'Ciudad Sandino','city_id'=>'12'],
            ['name'=>'El Crucero','city_id'=>'12'],
            ['name'=>'Managua','city_id'=>'12'],
            ['name'=>'Mateare','city_id'=>'12'],
            ['name'=>'San Francisco Libre','city_id'=>'12'],
            ['name'=>'San Rafael del Sur','city_id'=>'12'],
            ['name'=>'Ticuantepe','city_id'=>'12'],
            ['name'=>'Tipitapa','city_id'=>'12'],
            ['name'=>'Villa El Carmen','city_id'=>'12'],
            ['name'=>'Catarina','city_id'=>'13'],
            ['name'=>'La Concepción','city_id'=>'13'],
            ['name'=>'Masatepe','city_id'=>'13'],
            ['name'=>'Masaya','city_id'=>'13'],
            ['name'=>'Nandasmo','city_id'=>'13'],
            ['name'=>'Nindirí','city_id'=>'13'],
            ['name'=>'Niquinohomo','city_id'=>'13'],
            ['name'=>'San Juan de Oriente','city_id'=>'13'],
            ['name'=>'Tisma','city_id'=>'13'],
            ['name'=>'Ciudad Darío','city_id'=>'14'],
            ['name'=>'El Tuma - La Dalia','city_id'=>'14'],
            ['name'=>'Esquipulas','city_id'=>'14'],
            ['name'=>'Matagalpa','city_id'=>'14'],
            ['name'=>'Matiguás','city_id'=>'14'],
            ['name'=>'Muy Muy','city_id'=>'14'],
            ['name'=>'Rancho Grande','city_id'=>'14'],
            ['name'=>'Río Blanco','city_id'=>'14'],
            ['name'=>'San Dionisio','city_id'=>'14'],
            ['name'=>'San Isidro','city_id'=>'14'],
            ['name'=>'San Ramón','city_id'=>'14'],
            ['name'=>'Sébaco','city_id'=>'14'],
            ['name'=>'Terrabona','city_id'=>'14'],
            ['name'=>'Ciudad Antigua','city_id'=>'15'],
            ['name'=>'Dipilto','city_id'=>'15'],
            ['name'=>'El Jícaro','city_id'=>'15'],
            ['name'=>'Jalapa','city_id'=>'15'],
            ['name'=>'Macuelizo','city_id'=>'15'],
            ['name'=>'Mozonte','city_id'=>'15'],
            ['name'=>'Murra','city_id'=>'15'],
            ['name'=>'Ocotal','city_id'=>'15'],
            ['name'=>'Quilalí','city_id'=>'15'],
            ['name'=>'San Fernando','city_id'=>'15'],
            ['name'=>'Santa María','city_id'=>'15'],
            ['name'=>'Wiwilí','city_id'=>'15'],
            ['name'=>'El Almendro','city_id'=>'16'],
            ['name'=>'El Castillo','city_id'=>'16'],
            ['name'=>'Morrito','city_id'=>'16'],
            ['name'=>'San Carlos','city_id'=>'16'],
            ['name'=>'San Juan del Norte','city_id'=>'16'],
            ['name'=>'San Miguelito','city_id'=>'16'],
            ['name'=>'Altagracia','city_id'=>'17'],
            ['name'=>'Belén','city_id'=>'17'],
            ['name'=>'Buenos Aires','city_id'=>'17'],
            ['name'=>'Cárdenas','city_id'=>'17'],
            ['name'=>'Moyogalpa','city_id'=>'17'],
            ['name'=>'Potosí','city_id'=>'17'],
            ['name'=>'Rivas','city_id'=>'17'],
            ['name'=>'San Jorge','city_id'=>'17'],
            ['name'=>'San Juan del Sur','city_id'=>'17'],
            ['name'=>'Tola','city_id'=>'17']
        ];
        DB::table('municipalities')->insert($municipalities);
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
        DB::commit();
    }
}
